# Generated by Django 4.1.4 on 2022-12-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('card_series', models.PositiveIntegerField()),
                ('number_card', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVATED', 'ACTIVATED'), ('NOT ACTIVATED', 'NOT ACTIVATED'), ('EXPIRED', 'EXPIRED')], default='ACTIVATED', max_length=100)),
            ],
        ),
    ]
